### ISSUE TITLE
Camera support

### ISSUE THREAD

**Issue by goncalopp** [richardbunt/Telemachus#42]
Hi,

I noticed on the forums you mentioned in January you had a working prototype integrating the MechJeb Hull Camera, which is really cool! I noticed the code wasn't updated since November - are you developing that in private? Would you mind sharing it (in a development branch)?

**Comment by richardbunt** [comment]
The prototype was never completed due to time constraints on my end, and the code that I wrote back in January last year is now obsolete.

Another KSP player investigated the possibility of streaming camera data and found that Telemachus was not suited to this task. However, they wrote their own KSP modification which avoided some of the limitations of Telemachus; you can find the KSP forum thread for this project [here](http://forum.kerbalspaceprogram.com/threads/79605) and the github page [here](https://github.com/withorwithoutgod/GoAtThrottleUp).
